# Generated by Django 2.1.5 on 2019-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190216_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.CharField(max_length=15)),
                ('msg', models.TextField(max_length=500)),
            ],
        ),
    ]
