# Generated by Django 2.1.5 on 2019-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('cate', models.CharField(blank=True, default='', max_length=50)),
                ('subcate', models.CharField(blank=True, default='', max_length=50)),
                ('img', models.ImageField(default='', upload_to='shop/images')),
                ('price', models.CharField(default='', max_length=20)),
                ('desc', models.TextField(blank=True, max_length=1000)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
