# Generated by Django 2.1.5 on 2019-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartItem',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
