# Generated by Django 2.1.5 on 2019-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartItem',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
