# Generated by Django 2.1.5 on 2019-04-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190421_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Add1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Add2',
        ),
    ]
