# Generated by Django 2.1.5 on 2019-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190424_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
